### ISSUE TITLE
fsamp vs dt

### ISSUE THREAD

**Issue by andreas-wuestefeld** [DAS-RCN/RCN_DASformat#2]
Please indicate your preference here, whether temporal sample spacing [s] or sampling rate [Hz] should be used

**Comment by rcasey-earthscope** [comment]
Hz would be my preference.

1)  It's what I see more commonly used in representing sample rate, prior to time steps being actually implemented.
2) You can represent high sample rates with a non-fractional value, aiding in precision of representation.

**Comment by andreas-wuestefeld** [comment]
done
